(import ../../src.server/graph)
(import ../../src.server/json)
(import ../../src.server/config)
(import ./harness :as t)

(t/test "file commands resolve the original path and reject mismatched or deleted files"
  (def root (string (string/trimr (or (os/getenv "TMPDIR") "/tmp") "/") "/vz-file-test-" (os/getpid)))
  (os/mkdir root)
  (def filename "a 'quoted' file.txt")
  (def path (string root "/" filename))
  (spit path "text")
  (config/initialize (string root "/visualize_config"))
  (def w (graph/start root (fn [_] nil)))
  (defer (do (:stop w)
             (when (os/stat path) (os/rm path))
             (when (os/stat (string root "/visualize_config")) (os/rm (string root "/visualize_config")))
             (os/rmdir root))
    (t/is= (os/realpath path) (:call w :file {"node" "a.quoted.file.txt" "file" filename}))
    (t/ok (try (do (:call w :file {"node" "a.quoted.file.txt" "file" "other.txt"}) false) ([_] true)))
    (os/rm path)
    (t/ok (try (do (:call w :file {"node" "a.quoted.file.txt" "file" filename}) false) ([_] true)))))
(t/test "pane metadata preserves graph generation and the cached animated drawing"
  (def root (string "/tmp/vz-graph-cache-" (os/getpid)))
  (os/mkdir root)
  (def path (string root "/visualize_config"))
  (def source (string root "/a.py"))
  (spit path "animate\n")
  (spit source "x = 1\n")
  (def renderer (graph/start root (fn [_] nil)))
  (defer (do (:stop renderer) (os/rm source) (os/rm path) (os/rmdir root))
    (:call renderer :draw)
    (spit source "x = 222\n")
    (def changed (:call renderer :draw))
    (t/ok (string/find `class="node fresh"` (changed 3)))
    (config/write-config path (config/remember-placements (config/read-config path) {"a" ["bottom" 0 400 300]}))
    (def cached (:call renderer :draw))
    (t/is= (changed 4) (cached 4) "pane placement does not advance source generation")
    (t/is= (changed 3) (cached 3) "the cached drawing keeps its animation markers")
    (config/write-config path ["lines"])
    (def next (:call renderer :draw))
    (t/ok (> (next 4) (cached 4)) "graph commands do advance generation")
    (t/ok (not (string/find `class="node fresh"` (next 3))))))
