(import ../../src.server/graph)
(import ../../src.server/json)
(import ../../src.server/config)
(import ./harness :as t)

(t/test "the graph watcher tracks nested hide changes even when the nested config is hidden"
  (def root (string "/tmp/vz-hidden-watch-" (os/getpid)))
  (def dir (string root "/app"))
  (os/mkdir root)
  (os/mkdir dir)
  (def path (string root "/visualize_config"))
  (def nested (string dir "/visualize_config"))
  (def source (string dir "/a.py"))
  (spit path "visualize app\nhide app.visualize_config\n")
  (spit nested "hide a\n")
  (spit source "x = 1\n")
  (var generation 0)
  (def w (graph/start root (fn [value] (set generation value))))
  (defer (do (:stop w) (os/rm source) (os/rm nested) (os/rm path)
             (os/rmdir dir) (os/rmdir root))
    (def first-draw (:call w :draw))
    (t/ok (not (string/find "app.a.py" (first-draw 3))))
    (spit source "x = 222\n")
    (t/is= (first-draw 4) ((:call w :draw) 4) "hidden edits preserve the cached graph")
    (spit nested "")
    (def deadline (+ (os/clock :monotonic) 3))
    (while (and (= generation (first-draw 4)) (< (os/clock :monotonic) deadline))
      (ev/sleep 0.05))
    (t/ok (> generation (first-draw 4)) "the watcher notices a change to an excluded nested config")
    (def restored (:call w :draw))
    (t/ok (string/find "app.a.py" (restored 3)))
    (spit nested "hide a\n")
    (def hidden (:call w :draw))
    (t/ok (> (hidden 4) (restored 4)))
    (t/ok (not (string/find "app.a.py" (hidden 3))))))

(t/test "file commands resolve the original path and reject mismatched or deleted files"
  (def root (string (string/trimr (or (os/getenv "TMPDIR") "/tmp") "/") "/vz-file-test-" (os/getpid)))
  (os/mkdir root)
  (def filename "a 'quoted' file.txt")
  (def path (string root "/" filename))
  (spit path "text")
  (config/initialize (string root "/visualize_config"))
  (def w (graph/start root (fn [_] nil)))
  (defer (do (:stop w)
             (when (os/stat path) (os/rm path))
             (when (os/stat (string root "/visualize_config")) (os/rm (string root "/visualize_config")))
             (os/rmdir root))
    (t/is= (os/realpath path) (:call w :file {"node" "a.quoted.file.txt" "file" filename}))
    (t/ok (try (do (:call w :file {"node" "a.quoted.file.txt" "file" "other.txt"}) false) ([_] true)))
    (os/rm path)
    (t/ok (try (do (:call w :file {"node" "a.quoted.file.txt" "file" filename}) false) ([_] true)))))
(t/test "pane metadata preserves graph generation and the cached animated drawing"
  (def root (string "/tmp/vz-graph-cache-" (os/getpid)))
  (os/mkdir root)
  (def path (string root "/visualize_config"))
  (def source (string root "/a.py"))
  (spit path "animate\n")
  (spit source "x = 1\n")
  (def renderer (graph/start root (fn [_] nil)))
  (defer (do (:stop renderer) (os/rm source) (os/rm path) (os/rmdir root))
    (:call renderer :draw)
    (spit source "x = 222\n")
    (def changed (:call renderer :draw))
    (t/ok (string/find `class="node fresh"` (changed 3)))
    (config/write-config path (config/remember-placements (config/read-config path) {"a" ["bottom" 0 400 300]}))
    (def cached (:call renderer :draw))
    (t/is= (changed 4) (cached 4) "pane placement does not advance source generation")
    (t/is= (changed 3) (cached 3) "the cached drawing keeps its animation markers")
    (config/write-config path ["lines"])
    (def next (:call renderer :draw))
    (t/ok (> (next 4) (cached 4)) "graph commands do advance generation")
    (t/ok (not (string/find `class="node fresh"` (next 3))))))
