(import ../../src.server/worker)
(import ../../src.server/json)
(import ../../src.server/config)
(import ./harness :as t)

(t/test "graph worker serializes edits and metadata without replacing either"
  (def root (string (string/trimr (or (os/getenv "TMPDIR") "/tmp") "/") "/vz-worker-test-" (os/getpid)))
  (os/mkdir root)
  (var generation 0)
  (def w (worker/start root (fn [n] (set generation n))))
  (defer (do (:stop w)
             (os/rm (string root "/visualize.conf"))
             (os/rmdir root))
    (:call w :notes [["harness" "/tmp/test.sock"]])
    (def positions {"harness" ["bottom" 2] "config" ["floating" 120 240]})
    (:call w :placements positions)
    (def documents {"harness" "/tmp/a 'quoted' markdown.md"})
    (:call w :markdown documents)
    (:call w :notes [["harness" "/tmp/test.sock"]])
    (:call w :label ["harness" "kept"])
    (def saved (json/decode (:call w :edit {"action" "run" "lines" ["(lines)"]})))
    (t/is= ["(lines)"] (filter |(not (empty? $)) (saved "lines")))
    (def lines (:call w :read))
    (t/is= positions (config/placements lines))
    (t/is= documents (config/markdown lines))
    (t/ok (some |(string/find "test.sock" $) lines))
    (t/ok (some |(string/find "kept" $) lines))
    (t/ok (> generation 0))
    (def before (string (slurp (string root "/visualize.conf"))))
    (:call w :edit {"action" "check" "lines" ["(hide test)"]})
    (t/is= before (string (slurp (string root "/visualize.conf"))))))

(t/test "file commands resolve the original path and reject mismatched or deleted files"
  (def root (string (string/trimr (or (os/getenv "TMPDIR") "/tmp") "/") "/vz-file-test-" (os/getpid)))
  (os/mkdir root)
  (def filename "a 'quoted' file.txt")
  (def path (string root "/" filename))
  (spit path "text")
  (def w (worker/start root (fn [_] nil)))
  (defer (do (:stop w)
             (when (os/stat path) (os/rm path))
             (when (os/stat (string root "/visualize.conf")) (os/rm (string root "/visualize.conf")))
             (os/rmdir root))
    (t/is= (os/realpath path) (:call w :file {"node" "a.quoted.file.txt" "file" filename}))
    (t/ok (try (do (:call w :file {"node" "a.quoted.file.txt" "file" "other.txt"}) false) ([_] true)))
    (os/rm path)
    (t/ok (try (do (:call w :file {"node" "a.quoted.file.txt" "file" filename}) false) ([_] true)))))
