(import ../visualize/worker)
(import ../visualize/json)
(import ./harness :as t)

(t/test "graph worker serializes edits and metadata without replacing either"
  (def root (string (string/trimr (or (os/getenv "TMPDIR") "/tmp") "/") "/vz-worker-test-" (os/getpid)))
  (os/mkdir root)
  (var generation 0)
  (def w (worker/start root (fn [n] (set generation n))))
  (defer (do (:stop w)
             (os/rm (string root "/visualize.conf"))
             (os/rmdir root))
    (:call w :notes [["harness" "/tmp/test.sock"]])
    (:call w :label ["harness" "kept"])
    (def saved (json/decode (:call w :edit {"action" "run" "lines" ["(lines)"]})))
    (t/is= ["(lines)"] (filter |(not (empty? $)) (saved "lines")))
    (def lines (:call w :read))
    (t/ok (some |(string/find "test.sock" $) lines))
    (t/ok (some |(string/find "kept" $) lines))
    (t/ok (> generation 0))
    (def before (string (slurp (string root "/visualize.conf"))))
    (:call w :edit {"action" "check" "lines" ["(hide test)"]})
    (t/is= before (string (slurp (string root "/visualize.conf"))))))
