#!/bin/sh
#
# Run visualize on a directory, building the runtime first if it is not built.
#
#     ./visualize                 the current directory
#     ./visualize ~/code/project  somewhere else

set -e

here=$(cd "$(dirname "$0")" && pwd)

"$here/build"

exec "$here/external-src/janet/janet" "$here/src/visualize/core.janet" "$@"
