(import ./libvterm-test-api :as v)
(import ../src.server/json)

(def passed @[])
(def limitations @[])
(defn pass [name] (array/push passed name))
(def terminal (v/create 6 40))
(assert terminal)
(defer (v/release terminal)
  (v/feed terminal "hello\rWORLD\e[2;1H\e[38;2;12;34;56mred\e[0m")
  (assert (deep= ["WORLD" "red"] (slice (string/split "\n" (v/capture terminal)) 0 2)))
  (assert (= 0x0c2238 ((v/at terminal 1 0) 8)))
  (pass "screen capture handles overwritten text and truecolor")
  (v/clean terminal)
  (v/feed terminal "\e[3;1HX")
  (assert (and (= 1 (v/dirty terminal 2)) (zero? (v/dirty terminal 0))))
  (pass "row damage identifies changed rows")
  (v/feed terminal "\e[?1049hALT")
  (assert (= 1 (v/info terminal 5)))
  (v/feed terminal "\e[?1049l")
  (assert (and (zero? (v/info terminal 5)) (string/has-prefix? "WORLD" (v/capture terminal))))
  (pass "alternate screen restores main screen")
  (v/feed terminal "\e[6n")
  (assert (string/find "\e[3;2R" (v/capture terminal v/replies)))
  (pass "cursor query returns terminal response")
  (v/feed terminal "\e[4;1Hé界")
  (assert (deep= [101 0x301] (slice (v/at terminal 3 0) 0 2)))
  (assert (= 2 ((v/at terminal 3 1) 6)))
  (pass "combining accents and wide CJK cells")
  (v/resized terminal 8 60)
  (assert (string/has-prefix? "WORLD" (v/capture terminal)))
  (pass "resize preserves basic screen contents")
  (v/feed terminal (string "\e[2J\e[H" (string/join (seq [i :range [0 40]] (string "line " i)) "\r\n")))
  (assert (pos? (v/info terminal 6)))
  (assert (not= 0 ((v/at terminal 0 0 1) 0)))
  (pass "scrollback callbacks retain readable cells")
  (repeat 20
    (each [rows cols] [[20 112] [30 80] [12 40] [24 112]]
      (v/resized terminal rows cols)
      (v/capture terminal)))
  (pass "80 resize transitions with scrollback")
  (assert (zero? (v/resize terminal 0 80)))
  (assert (zero? (v/cell terminal 0 -1 0 (buffer/new-filled 44 0))))
  (pass "invalid dimensions and cell coordinates rejected")
  (v/feed terminal "\e[?2026$p")
  (assert (string/find "\e[?2026;2$y" (v/capture terminal v/replies)))
  (pass "synchronized-output mode is supported")
  (v/feed terminal "\e[?u")
  (when (empty? (v/capture terminal v/replies))
    (array/push limitations "Kitty keyboard query receives no reply"))
  (v/feed terminal "\e[1;1H\e]8;;https://example.invalid\e\\link\e]8;;\e\\")
  (assert (string/has-prefix? "link" (v/capture terminal)))
  (when (pos? (v/info terminal 8))
    (array/push limitations "OSC 8 reaches fallback; text survives but link metadata is unavailable"))
  (assert (zero? (v/info terminal 9))))

(each [label content widths]
  [["ASCII line reflow" "abcdefghijklmnopqrstuvwxyz0123456789" [10 40]]
   ["emoji ZWJ" "👩‍💻" [40]]]
  (def terminal (v/create 12 40))
  (assert terminal)
  (defer (v/release terminal)
    (v/feed terminal content)
    (each width widths (v/resized terminal 12 width))
    (when (and (= label "emoji ZWJ") (not= (v/info terminal 3) 2))
      (array/push limitations (string "emoji ZWJ occupies " (v/info terminal 3) " columns instead of 2")))
    (if (= content (string/replace-all "\n" "" (v/capture terminal)))
      (pass label)
      (array/push limitations (string label " does not round-trip as the original text")))))

(def terminal (v/create 6 40))
(assert terminal)
(defer (v/release terminal)
  (v/feed terminal (string/join (seq [i :range [0 2100]] (string "history " i)) "\r\n"))
  (assert (= 2000 (v/info terminal 6)))
  (v/resized terminal 20 40)
  (assert (< (v/info terminal 6) 2000))
  (pass "bounded history evicts old rows and restores rows on growth")
  (v/feed terminal "\e[2J\e[H\e]8;;https://example.invalid\e\\linked text\e]8;;\e\\")
  (repeat 20
    (each width [80 20 112]
      (v/resized terminal 20 width)
      (assert (string/find "linked text" (v/capture terminal)))))
  (assert (zero? (v/info terminal 9)))
  (pass "unfiltered OSC 8 text survives 60 resize transitions"))

(def replays @[])
(each path (slice (dyn :args) (min 2 (length (dyn :args))))
  (def chunks (map v/decode-base64 (json/decode (slurp path))))
  (repeat 20
    (def terminal (v/create (if (string/find "fulfillment" path) 20 30) 112))
    (assert terminal)
    (defer (v/release terminal)
      (each chunk chunks (v/feed terminal chunk) (v/capture terminal v/replies))
      (each [rows cols] [[30 98] [12 40] [24 80] [20 112]]
        (v/resized terminal rows cols)
        (v/capture terminal))
      (assert (zero? (v/info terminal 9)))))
  (array/push replays {"fixture" (last (string/split "/" path))
                      "bytes" (sum (map length chunks)) "cycles" 20
                      "result" "no crash, valid cursor, capture readable"}))

(def terminal (v/create 6 40))
(def split-terminal (v/create 6 40))
(assert (and terminal split-terminal))
(defer (do (v/release terminal) (v/release split-terminal))
  (def payload "café 界\e[31m red\e[0m\r\nnext")
  (v/feed terminal payload)
  (for i 0 (length payload) (v/feed split-terminal (string/slice payload i (inc i))))
  (assert (= (v/capture terminal) (v/capture split-terminal)))
  (for row 0 6
    (for col 0 40 (assert (deep= (v/at terminal row col) (v/at split-terminal row col)))))
  (pass "byte-split UTF-8 and escape sequences match whole-buffer cells"))

(print (json/encode {"passed" passed "limitations" limitations "replays" replays}))
